const paddleOcrDocumentOptionalPayload = <String, Object?>{
  'useDocOrientationClassify': true,
  'useDocUnwarping': true,
  'useTextlineOrientation': true,
  'useLayoutDetection': true,
  'useChartRecognition': false,
  'useSealRecognition': false,
  'useOcrForImageBlock': false,
  'mergeTables': true,
  'relevelTitles': false,
  'layoutShapeMode': 'auto',
  'promptLabel': 'ocr',
  'repetitionPenalty': 1,
  'temperature': 0,
  'topP': 1,
  'minPixels': 147384,
  'maxPixels': 2822400,
  'layoutNms': true,
  'restructurePages': true,
};
